const express = require('express')
// const router = express.Router()
const router = express.Router()
const register = require('./register')
const login = require('./login')
const createEvent = require('./createEvent')
const deleteEvent = require('./deleteEvent')
const logout = require('./logout')
const userTasks = require('./userTasks')
const isLogged = require('./isLogged')
const getEvents = require('./getEvents')
const getTask = require('./getTask')
const addVolunteer = require('./addVolunteer')
const getTasks = require('./getTasks')
const isCompleted = require('./isCompleted')

router.post('/register',register)
router.post('/login',login)
router.post('/createEvent',createEvent)
router.post('/deleteEvent',deleteEvent)
router.post('/addVolunteer',addVolunteer)
router.post('/isCompleted',isCompleted)
router.get('/logout',logout)
router.get('/userTasks',userTasks)
router.get('/isLogged',isLogged)
router.get('/getEvents',getEvents)
router.get('/getTask/:event_id',getTask)
router.get('/getTasks',getTasks)


module.exports = router